### ISSUE TITLE
PyCryptoScraper improvement

### ISSUE THREAD

**Issue by erotavlasme** [patrick0585/PyCryptoScraper#1]
Hi,
I was looking for a crawler that is able to parse coingecko data. In particular, not only the price, but also the information about developer, liquidity and public interest.
I would like to use python so I can learn it in the meantime. I know C++ and java quite well. I found your code and I tried it with python 2.7.x and python 3.6.x, but in both cases it does not work.
`python Scraper.py -c "[{'name':'bitcoin','tags':['usd','eur']}]"
Traceback (most recent call last):
  File "Scraper.py", line 30, in <module>
    valid_currencies, errors = DataSchema(many=True).load(currencies_to_scrape)
ValueError: not enough values to unpack (expected 2, got 1)`

`python test_CryptoScraper.py
Traceback (most recent call last):
  File "test_CryptoScraper.py", line 5, in <module>
    from scraper.CryptoScraper import CryptoScraper
ImportError: No module named scraper.CryptoScraper`
So before to start to read the code, I wonder to know if it works.
Maybe can we work together in order to have a working updated version?

**Comment by patrick0585** [comment]
Thank you for your interest in my code for the first time.
I made a few adjustments to the code because the HTML content of the Coingecko page has changed.
If I run the code locally it works for me.

```
python Scraper.py -c "[{'name':'bitcoin','tags':['usd','eur']}]"
[{"trading_volume": "3,673,436,869", "code": "BTC", "exchange_rate": "USD", "market_capitalisation": "161,869,206,379", "currency": "Bitcoin", "date": 1520846700}, {"trading_volume": "2,979,520,971", "code": "BTC", "exchange_rate": "EUR", "market_capitalisation": "131,291,951,425", "currency": "Bitcoin", "date": 1520846700}]
```

You can also make improvements to the code, or add to useful extensions.

**Comment by erotavlasme** [comment]
Thank you for your support. However your code does not work.
So I decided to write my own code by using [pyquery](https://pythonhosted.org/pyquery/api.html) and I solved my problem.
